#-------------------------------
# General Site Settings
title: Memory Note
logo: try_log.PNG # You can add own logo.
description: 필요한 정보를 기록하는 공간


#-------------------------------
# Author Settings
author:
  name: ParkJeongBin
  # image: blanck.jpg
  say-hello: <strong>박정빈</strong>
  bio: 데이터를 좋아하는 Data enthusiast.

#-------------------------------
# Contact links
twitter: https://www.linkedin.com/in/%EC%A0%95%EB%B9%88-%EB%B0%95-9a0458209/
facebook: https://www.kaggle.com/jeongbinpark # Add your Facebook handle
dribbble: https://github.com/wjdqlsdlsp # Add your Dribbble handle

#-------------------------------

#-------------------------------
# Google Analytics
google-analytics: G-KQYDN19HGC


